from networksecurity.entity.artifact_entity import DataIngestionArtifact
from networksecurity.entity.config_entity import DataV
from networksecurity.exception.exception import NetworkSecurityException